apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: scp-keyvault-01
  labels: 
    azure.azureauthority.in: aks-apps
    app: asset-manager
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: fda95b6e-012a-4642-819b-af3236d76217
    keyvaultName: knproject3chiow
    objects:  |
      array:
        - |
          objectName: asset-manager-connectionstrings
          objectType: secret
          objectAlias: connectionstrings.json
    tenantId: cf36141c-ddd7-45a7-b073-111f66d0b30c